#!/bin/bash
# OCTCS 团队技能安装脚本
# 由于 API 限流，建议分批安装

echo "🚀 OCTCS 团队技能安装脚本"
echo "=========================="
echo ""
echo "⚠️ 注意: 如果遇到 API rate limit，请等待 1-2 分钟后重试"
echo ""

# 核心技能（高优先级）
echo "📦 核心技能安装命令:"
echo "--------------------"
echo ""
echo "1. Google Workspace 集成 (推荐首先安装)"
echo "   npx clawhub install gog"
echo ""
echo "2. Obsidian 知识库管理"
echo "   npx clawhub install obsidian"
echo ""
echo "3. PDF 文档处理"
echo "   npx clawhub install nano-pdf"
echo ""
echo "4. 语音转文字 (会议记录)"
echo "   npx clawhub install openai-whisper"
echo ""
echo "5. MCP 工具管理"
echo "   npx clawhub install mcporter"
echo ""

# 效率技能（中优先级）
echo ""
echo "📦 效率技能安装命令:"
echo "--------------------"
echo ""
echo "6. Trello 项目管理"
echo "   npx clawhub install trello"
echo ""
echo "7. ClawHub 技能市场"
echo "   npx clawhub install clawhub"
echo ""
echo "8. Things 任务管理 (macOS)"
echo "   npx clawhub install things-mac"
echo ""
echo "9. Apple 提醒事项"
echo "   npx clawhub install apple-reminders"
echo ""
echo "10. Tmux 终端管理"
echo "   npx clawhub install tmux"
echo ""

# 可选技能（低优先级）
echo ""
echo "📦 可选技能安装命令:"
echo "--------------------"
echo ""
echo "11. AI 图片生成"
echo "   npx clawhub install nano-banana-pro"
echo ""
echo "12. 技术博客监控"
echo "   npx clawhub install blogwatcher"
echo ""
echo "13. Sonos 音响控制"
echo "   npx clawhub install sonoscli"
echo ""

echo ""
echo "✅ 安装建议:"
echo "------------"
echo "1. 每次安装间隔 10-30 秒，避免触发限流"
echo "2. 先安装核心技能 (1-5)，满足基本需求"
echo "3. 根据实际需要安装效率技能 (6-10)"
echo "4. 可选技能根据项目类型选择性安装"
echo ""
echo "💡 安装完成后，使用 'openclaw skills list' 查看已安装技能"
echo ""
